name: TGTTOS
version: '${project.version}'
main: io.github.cardsandhuskers.tgttos.TGTTOS
api-version: 1.19
authors: [ cardsandhuskers ]
description: To get to the Other Side and Press the Button
depend: [PlaceholderAPI, Teams]
softdepend: [Multiverse-Core]
commands:
  setTGTTOSPos1:
    description: sets position 1 of the arena
    usage: /<command> [arena]
  setTGTTOSPos2:
    description: sets position 2 of the arena
    usage: /<command> [arena]
  setTGTTOSSpawnPoint:
    description: sets the spawn point
    usage: /<command>
  setTGTTOSArenaSpawnPoint:
    description: sets the spawn point for the arena
    usage: /<command> [arena]
  startTGTTOS:
    description: starts the game
    usage: /<command> [multiplier]
  setTGTTOSLobby:
    description: sets the lobby point to return players to
    usage: /<command>
  reloadTGTTOS:
    description: reloads the config for the game
    usage: /<command>
  cancelTGTTOS:
    description: cancels the game
    usage: /<command>
